### ISSUE TITLE
Requires.NotNull should accept values of type `T?`

### ISSUE THREAD

**Issue by 9at8** [microsoft/vs-validation#160]
https://dotnetfiddle.net/rB8FPD

In the following code, the Requires.NotNull call displays a warning

<img width="461" alt="image" src="https://user-images.githubusercontent.com/8235156/206822731-8a60deae-adf2-4f2a-a359-95bafeac1dd1.png">

The `Requires.NotNull` function should accept values of type `T?` instead of `T`

```cs
#nullable enable

using System;
using Microsoft;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine("Hello World");
		
		Foo? str = null;

		Requires.NotNull(str, "");
	}
	
	private class Foo {
	}
}
```

**Comment by AArnott** [comment]
Thanks for the feedback, but this decision was carefully considered in #37 and the design we have is intentional. 
`Requires` is for argument validation, and if you call `Requires.NotNull` on an argument, the parameter should _not_ be declared as nullable. That is why `Requires.NotNull` does not take nullable arguments -- it helps ensure your parameter declaration is honest about your nullable expectations.
In your sample code, `Requires` isn't the right class to use. You should use `Assumes` for validating your internal state.
